//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Condominium2000.Resources.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DeleteUser {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DeleteUser() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    var temp = new global::System.Resources.ResourceManager("Condominium2000.Resources.Account.DeleteUser", typeof(DeleteUser).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta Bort.
        /// </summary>
        public static string BUTTON_DELETE {
            get {
                return ResourceManager.GetString("BUTTON_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort användaren misslyckades. Var god rätta till felen och försök igen..
        /// </summary>
        public static string ERROR_DELETE_USER {
            get {
                return ResourceManager.GetString("ERROR_DELETE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan ej ta bort sista Superadmin användaren!.
        /// </summary>
        public static string ERROR_INTERNAL_LAST_SUPERADMIN {
            get {
                return ResourceManager.GetString("ERROR_INTERNAL_LAST_SUPERADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fel uppstod när användare skulle tas bort..
        /// </summary>
        public static string ERROR_INTERNAL_NOT_DELETE_MODEL {
            get {
                return ResourceManager.GetString("ERROR_INTERNAL_NOT_DELETE_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Användaren kunde inte hittas..
        /// </summary>
        public static string ERROR_INTERNAL_NOT_FIND_USER {
            get {
                return ResourceManager.GetString("ERROR_INTERNAL_NOT_FIND_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string LABEL_EMAIL {
            get {
                return ResourceManager.GetString("LABEL_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Förnamn:.
        /// </summary>
        public static string LABEL_FIRST_NAME {
            get {
                return ResourceManager.GetString("LABEL_FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godkänd:.
        /// </summary>
        public static string LABEL_IS_APPROVED {
            get {
                return ResourceManager.GetString("LABEL_IS_APPROVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efternamn:.
        /// </summary>
        public static string LABEL_LAST_NAME {
            get {
                return ResourceManager.GetString("LABEL_LAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll:.
        /// </summary>
        public static string LABEL_ROLE {
            get {
                return ResourceManager.GetString("LABEL_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Användarnamn:.
        /// </summary>
        public static string LABEL_USER_NAME {
            get {
                return ResourceManager.GetString("LABEL_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Användaren har blivit borttagen!.
        /// </summary>
        public static string SUCCESS_USER_DELETED {
            get {
                return ResourceManager.GetString("SUCCESS_USER_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort Användare:.
        /// </summary>
        public static string TEXT_DELETE_USER {
            get {
                return ResourceManager.GetString("TEXT_DELETE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Är du säker på att du vill ta bort nedanstående användare?.
        /// </summary>
        public static string TEXT_HELP_1 {
            get {
                return ResourceManager.GetString("TEXT_HELP_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort användare.
        /// </summary>
        public static string VIEW_BAG_TITLE {
            get {
                return ResourceManager.GetString("VIEW_BAG_TITLE", resourceCulture);
            }
        }
    }
}
