//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Condominium2000.Resources.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LogOn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogOn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    var temp = new global::System.Resources.ResourceManager("Condominium2000.Resources.Account.LogOn", typeof(LogOn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logga In.
        /// </summary>
        public static string BUTTON_LOG_IN {
            get {
                return ResourceManager.GetString("BUTTON_LOG_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Användarnamnet eller lösenordet är fel..
        /// </summary>
        public static string ERROR_INTERNAL_USER_PASS {
            get {
                return ResourceManager.GetString("ERROR_INTERNAL_USER_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inloggningen misslyckades. Var god rätta till felen och försök igen..
        /// </summary>
        public static string ERROR_LOG_IN {
            get {
                return ResourceManager.GetString("ERROR_LOG_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logga In.
        /// </summary>
        public static string HEADER_DEFAULT {
            get {
                return ResourceManager.GetString("HEADER_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lösenord:.
        /// </summary>
        public static string LABEL_PASSWORD {
            get {
                return ResourceManager.GetString("LABEL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kom ihåg uppgifter?.
        /// </summary>
        public static string LABEL_REMEMBER_ME {
            get {
                return ResourceManager.GetString("LABEL_REMEMBER_ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Authenticator Kod.
        /// </summary>
        public static string LABEL_TWO_FACTOR {
            get {
                return ResourceManager.GetString("LABEL_TWO_FACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Användarnamn:.
        /// </summary>
        public static string LABEL_USER_NAME {
            get {
                return ResourceManager.GetString("LABEL_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Konto:.
        /// </summary>
        public static string TEXT_ACCOUNT_INFO {
            get {
                return ResourceManager.GetString("TEXT_ACCOUNT_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Var vänlig skriv in användarnamn och lösenord..
        /// </summary>
        public static string TEXT_HELP_1 {
            get {
                return ResourceManager.GetString("TEXT_HELP_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observera att endast medlemmar i styrelsen har tillgång till denna funktion!.
        /// </summary>
        public static string TEXT_HELP_2 {
            get {
                return ResourceManager.GetString("TEXT_HELP_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrera.
        /// </summary>
        public static string TEXT_HELP_REGISTER {
            get {
                return ResourceManager.GetString("TEXT_HELP_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logga In.
        /// </summary>
        public static string VIEW_BAG_TITLE {
            get {
                return ResourceManager.GetString("VIEW_BAG_TITLE", resourceCulture);
            }
        }
    }
}
