//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Condominium2000.Resources.Society {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _SubMenuPartial {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _SubMenuPartial() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    var temp = new global::System.Resources.ResourceManager("Condominium2000.Resources.Society._SubMenuPartial", typeof(_SubMenuPartial).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        public static string HEADING_NAVIGATION {
            get {
                return ResourceManager.GetString("HEADING_NAVIGATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Årsstämma.
        /// </summary>
        public static string TEXT_ANNUAL_MEETING {
            get {
                return ResourceManager.GetString("TEXT_ANNUAL_MEETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Årsredovisning.
        /// </summary>
        public static string TEXT_ANNUAL_REPORT {
            get {
                return ResourceManager.GetString("TEXT_ANNUAL_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styrelsen.
        /// </summary>
        public static string TEXT_SOCIETY {
            get {
                return ResourceManager.GetString("TEXT_SOCIETY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Förening.
        /// </summary>
        public static string TEXT_UNION {
            get {
                return ResourceManager.GetString("TEXT_UNION", resourceCulture);
            }
        }
    }
}
