//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Condominium2000.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _FooterPartial {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _FooterPartial() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Condominium2000.Resources.Shared._FooterPartial", typeof(_FooterPartial).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktinformation.
        /// </summary>
        public static string HEADING_CONTACT {
            get {
                return ResourceManager.GetString("HEADING_CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookies.
        /// </summary>
        public static string HEADING_COOKIES {
            get {
                return ResourceManager.GetString("HEADING_COOKIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSS.
        /// </summary>
        public static string HEADING_RSS {
            get {
                return ResourceManager.GetString("HEADING_RSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condominium2000.
        /// </summary>
        public static string HEADING_WEB {
            get {
                return ResourceManager.GetString("HEADING_WEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress, 123 34 Mauris.
        /// </summary>
        public static string TEXT_CONTACT_ADRESS {
            get {
                return ResourceManager.GetString("TEXT_CONTACT_ADRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact@something.com.
        /// </summary>
        public static string TEXT_CONTACT_EMAIL {
            get {
                return ResourceManager.GetString("TEXT_CONTACT_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to According to the Electronic Communications Act, which entered into force on 25 July 2003, everyone who visits a website with cookies should be informed about:.
        /// </summary>
        public static string TEXT_CONTACT_INFO_1 {
            get {
                return ResourceManager.GetString("TEXT_CONTACT_INFO_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - that the website contain cookies,.
        /// </summary>
        public static string TEXT_CONTACT_INFO_2 {
            get {
                return ResourceManager.GetString("TEXT_CONTACT_INFO_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - what the cookies are used for and.
        /// </summary>
        public static string TEXT_CONTACT_INFO_3 {
            get {
                return ResourceManager.GetString("TEXT_CONTACT_INFO_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - how cookies can be avoided..
        /// </summary>
        public static string TEXT_CONTACT_INFO_4 {
            get {
                return ResourceManager.GetString("TEXT_CONTACT_INFO_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0734 - 12 34 56.
        /// </summary>
        public static string TEXT_CONTACT_PHONE {
            get {
                return ResourceManager.GetString("TEXT_CONTACT_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Announcements.
        /// </summary>
        public static string TEXT_RSS_ALL_ANNOUNCEMENTS {
            get {
                return ResourceManager.GetString("TEXT_RSS_ALL_ANNOUNCEMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All News.
        /// </summary>
        public static string TEXT_RSS_ALL_NEWS {
            get {
                return ResourceManager.GetString("TEXT_RSS_ALL_NEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.Condominium2000.se.
        /// </summary>
        public static string TEXT_WEB_INFO_1 {
            get {
                return ResourceManager.GetString("TEXT_WEB_INFO_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sollicitudin dignissim..
        /// </summary>
        public static string TEXT_WEB_INFO_2 {
            get {
                return ResourceManager.GetString("TEXT_WEB_INFO_2", resourceCulture);
            }
        }
    }
}
