//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Condominium2000.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _MenuPartial {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _MenuPartial() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    var temp = new global::System.Resources.ResourceManager("Condominium2000.Resources.Shared._MenuPartial", typeof(_MenuPartial).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menu_kontakt.
        /// </summary>
        public static string CLASS_CONTACT {
            get {
                return ResourceManager.GetString("CLASS_CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menu_kontakt_sel.
        /// </summary>
        public static string CLASS_CONTACT_SEL {
            get {
                return ResourceManager.GetString("CLASS_CONTACT_SEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menu_forum.
        /// </summary>
        public static string CLASS_FORUM {
            get {
                return ResourceManager.GetString("CLASS_FORUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menu_forum_sel.
        /// </summary>
        public static string CLASS_FORUM_SEL {
            get {
                return ResourceManager.GetString("CLASS_FORUM_SEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menu_nyheter.
        /// </summary>
        public static string CLASS_NEWS {
            get {
                return ResourceManager.GetString("CLASS_NEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menu_nyheter_sel.
        /// </summary>
        public static string CLASS_NEWS_SEL {
            get {
                return ResourceManager.GetString("CLASS_NEWS_SEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menu_boende.
        /// </summary>
        public static string CLASS_RESIDENT {
            get {
                return ResourceManager.GetString("CLASS_RESIDENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menu_boende_sel.
        /// </summary>
        public static string CLASS_RESIDENT_SEL {
            get {
                return ResourceManager.GetString("CLASS_RESIDENT_SEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menu_forening.
        /// </summary>
        public static string CLASS_SOCIETY {
            get {
                return ResourceManager.GetString("CLASS_SOCIETY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menu_forening_sel.
        /// </summary>
        public static string CLASS_SOCIETY_SEL {
            get {
                return ResourceManager.GetString("CLASS_SOCIETY_SEL", resourceCulture);
            }
        }
    }
}
