//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Condominium2000.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EditLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    var temp = new global::System.Resources.ResourceManager("Condominium2000.Resources.Shared.EditLabels", typeof(EditLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hantera Årsmöten.
        /// </summary>
        public static string LABEL_ADMIN_ANNUAL_MEETING {
            get {
                return ResourceManager.GetString("LABEL_ADMIN_ANNUAL_MEETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hantera Årsredovisningar.
        /// </summary>
        public static string LABEL_ADMIN_ANNUAL_REPORTS {
            get {
                return ResourceManager.GetString("LABEL_ADMIN_ANNUAL_REPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hantera Medlemmar.
        /// </summary>
        public static string LABEL_ADMIN_BOARD_MEMBER {
            get {
                return ResourceManager.GetString("LABEL_ADMIN_BOARD_MEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hantera Galleri-bilder.
        /// </summary>
        public static string LABEL_ADMIN_GALLERY_IMAGES {
            get {
                return ResourceManager.GetString("LABEL_ADMIN_GALLERY_IMAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hantera Frågor.
        /// </summary>
        public static string LABEL_ADMIN_QUESTIONS {
            get {
                return ResourceManager.GetString("LABEL_ADMIN_QUESTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta Bort Nyhet.
        /// </summary>
        public static string LABEL_DELETE_NEWS {
            get {
                return ResourceManager.GetString("LABEL_DELETE_NEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editera Utrop.
        /// </summary>
        public static string LABEL_EDIT_ANNOUNCEMENT {
            get {
                return ResourceManager.GetString("LABEL_EDIT_ANNOUNCEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editera Information.
        /// </summary>
        public static string LABEL_EDIT_ANNUAL_MEETING_INFO {
            get {
                return ResourceManager.GetString("LABEL_EDIT_ANNUAL_MEETING_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editera Information.
        /// </summary>
        public static string LABEL_EDIT_ANNUAL_REPORT_INFO {
            get {
                return ResourceManager.GetString("LABEL_EDIT_ANNUAL_REPORT_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editera Information.
        /// </summary>
        public static string LABEL_EDIT_BOARD_FORM_INFO {
            get {
                return ResourceManager.GetString("LABEL_EDIT_BOARD_FORM_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editera Information.
        /// </summary>
        public static string LABEL_EDIT_BOOK_ROOM_INFO {
            get {
                return ResourceManager.GetString("LABEL_EDIT_BOOK_ROOM_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editera Information.
        /// </summary>
        public static string LABEL_EDIT_CONTACT_INFO {
            get {
                return ResourceManager.GetString("LABEL_EDIT_CONTACT_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editera Information.
        /// </summary>
        public static string LABEL_EDIT_ERROR_FORM_INFO {
            get {
                return ResourceManager.GetString("LABEL_EDIT_ERROR_FORM_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editera FRQ.
        /// </summary>
        public static string LABEL_EDIT_FRQ {
            get {
                return ResourceManager.GetString("LABEL_EDIT_FRQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editera Information.
        /// </summary>
        public static string LABEL_EDIT_IT_FORM_INFO {
            get {
                return ResourceManager.GetString("LABEL_EDIT_IT_FORM_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editera Information.
        /// </summary>
        public static string LABEL_EDIT_LINKS_INFO {
            get {
                return ResourceManager.GetString("LABEL_EDIT_LINKS_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editera Nyhet.
        /// </summary>
        public static string LABEL_EDIT_NEWS {
            get {
                return ResourceManager.GetString("LABEL_EDIT_NEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editera Fråga.
        /// </summary>
        public static string LABEL_EDIT_QUESTION {
            get {
                return ResourceManager.GetString("LABEL_EDIT_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editera Information.
        /// </summary>
        public static string LABEL_EDIT_QUESTIONS_INFO {
            get {
                return ResourceManager.GetString("LABEL_EDIT_QUESTIONS_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editera Information.
        /// </summary>
        public static string LABEL_EDIT_RESIDENT_INFO {
            get {
                return ResourceManager.GetString("LABEL_EDIT_RESIDENT_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editera Information.
        /// </summary>
        public static string LABEL_EDIT_SOCIETY_INFO {
            get {
                return ResourceManager.GetString("LABEL_EDIT_SOCIETY_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editera Information.
        /// </summary>
        public static string LABEL_EDIT_UNION_INFO {
            get {
                return ResourceManager.GetString("LABEL_EDIT_UNION_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapa Utrop.
        /// </summary>
        public static string LABEL_NEW_ANNOUNCEMENT {
            get {
                return ResourceManager.GetString("LABEL_NEW_ANNOUNCEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapa Medlem.
        /// </summary>
        public static string LABEL_NEW_BOARD_MEMBER {
            get {
                return ResourceManager.GetString("LABEL_NEW_BOARD_MEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapa Nyhet.
        /// </summary>
        public static string LABEL_NEW_NEWS {
            get {
                return ResourceManager.GetString("LABEL_NEW_NEWS", resourceCulture);
            }
        }
    }
}
