//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Condominium2000.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    var temp = new global::System.Resources.ResourceManager("Condominium2000.Resources.Shared.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skicka.
        /// </summary>
        public static string BUTTON_SEND {
            get {
                return ResourceManager.GetString("BUTTON_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engelska.
        /// </summary>
        public static string BUTTON_TAB_EN {
            get {
                return ResourceManager.GetString("BUTTON_TAB_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svenska.
        /// </summary>
        public static string BUTTON_TAB_SV {
            get {
                return ResourceManager.GetString("BUTTON_TAB_SV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Översätt till Engelska.
        /// </summary>
        public static string BUTTON_TRANSLATE_ENGLISH {
            get {
                return ResourceManager.GetString("BUTTON_TRANSLATE_ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Översätt till Svenska.
        /// </summary>
        public static string BUTTON_TRANSLATE_SWEDISH {
            get {
                return ResourceManager.GetString("BUTTON_TRANSLATE_SWEDISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brödtext på Engelska:.
        /// </summary>
        public static string LABEL_CONTENT_EN {
            get {
                return ResourceManager.GetString("LABEL_CONTENT_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brödtext på Svenska:.
        /// </summary>
        public static string LABEL_CONTENT_SV {
            get {
                return ResourceManager.GetString("LABEL_CONTENT_SV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapad:.
        /// </summary>
        public static string LABEL_DATE_CREATED {
            get {
                return ResourceManager.GetString("LABEL_DATE_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skriv in de två orden på bilden nedan (för att undvika spambots):.
        /// </summary>
        public static string LABEL_RECAPTCHA {
            get {
                return ResourceManager.GetString("LABEL_RECAPTCHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underrubrik på Engelska:.
        /// </summary>
        public static string LABEL_SUB_TITLE_EN {
            get {
                return ResourceManager.GetString("LABEL_SUB_TITLE_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underrubrik på Svenska:.
        /// </summary>
        public static string LABEL_SUB_TITLE_SV {
            get {
                return ResourceManager.GetString("LABEL_SUB_TITLE_SV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubrik på Engelska:.
        /// </summary>
        public static string LABEL_TITLE_EN {
            get {
                return ResourceManager.GetString("LABEL_TITLE_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubrik på Svenska:.
        /// </summary>
        public static string LABEL_TITLE_SV {
            get {
                return ResourceManager.GetString("LABEL_TITLE_SV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vissa fält innehåller både text på svenska och engelska som måste fyllas i. Använd &quot;översätt&quot; för att med Google Translate översätta texten från det andra språket..
        /// </summary>
        public static string TEXT_HELP {
            get {
                return ResourceManager.GetString("TEXT_HELP", resourceCulture);
            }
        }
    }
}
