//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Condominium2000.Resources.AnnualMeeting {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Create {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Create() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    var temp = new global::System.Resources.ResourceManager("Condominium2000.Resources.AnnualMeeting.Create", typeof(Create).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spara.
        /// </summary>
        public static string BUTTON_SAVE {
            get {
                return ResourceManager.GetString("BUTTON_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapa årsstämma misslyckades. Var god rätta till felen och försök igen..
        /// </summary>
        public static string ERROR_CREATE_ANNUAL_MEETING {
            get {
                return ResourceManager.GetString("ERROR_CREATE_ANNUAL_MEETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Årsstämman kunde inte hittas..
        /// </summary>
        public static string ERROR_INTERNAL_NOT_FIND_ANNUAL_MEETING {
            get {
                return ResourceManager.GetString("ERROR_INTERNAL_NOT_FIND_ANNUAL_MEETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fel uppstod när årsstämman skulle skapas..
        /// </summary>
        public static string ERROR_INTERNAL_NOT_SAVE_MODEL {
            get {
                return ResourceManager.GetString("ERROR_INTERNAL_NOT_SAVE_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunde inte spara fil under vald URL!.
        /// </summary>
        public static string ERROR_INTERNAL_PATH_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_INTERNAL_PATH_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Årsstämman har skapats!.
        /// </summary>
        public static string SUCCESS_ANNUAL_MEETING_SAVED {
            get {
                return ResourceManager.GetString("SUCCESS_ANNUAL_MEETING_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Årsstämma.
        /// </summary>
        public static string TEXT_CREATE_ANNUAL_MEETING {
            get {
                return ResourceManager.GetString("TEXT_CREATE_ANNUAL_MEETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Använd fälten nedan för att skapa en årsstämma..
        /// </summary>
        public static string TEXT_HELP_1 {
            get {
                return ResourceManager.GetString("TEXT_HELP_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapa Årsstämma.
        /// </summary>
        public static string VIEW_BAG_TITLE {
            get {
                return ResourceManager.GetString("VIEW_BAG_TITLE", resourceCulture);
            }
        }
    }
}
