//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Condominium2000.Resources.Question {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminQuestions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminQuestions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    var temp = new global::System.Resources.ResourceManager("Condominium2000.Resources.Question.AdminQuestions", typeof(AdminQuestions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapa ny Fråga.
        /// </summary>
        public static string BUTTON_CREATE_QUESTION {
            get {
                return ResourceManager.GetString("BUTTON_CREATE_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta Bort.
        /// </summary>
        public static string BUTTON_DELETE_QUESTION {
            get {
                return ResourceManager.GetString("BUTTON_DELETE_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editera.
        /// </summary>
        public static string BUTTON_EDIT_QUESTION {
            get {
                return ResourceManager.GetString("BUTTON_EDIT_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spara.
        /// </summary>
        public static string BUTTON_SAVE {
            get {
                return ResourceManager.GetString("BUTTON_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redigera fråga misslyckades. Var god rätta till felen och försök igen..
        /// </summary>
        public static string ERROR_EDIT_QUESTION {
            get {
                return ResourceManager.GetString("ERROR_EDIT_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fel uppstod, kunde inte hitta vald fråga!.
        /// </summary>
        public static string ERROR_INTERNAL_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_INTERNAL_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vald fråga har ändrats!.
        /// </summary>
        public static string SUCCESS_SELECTED_QUESTION_SAVED {
            get {
                return ResourceManager.GetString("SUCCESS_SELECTED_QUESTION_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort:.
        /// </summary>
        public static string TABLE_DELETE {
            get {
                return ResourceManager.GetString("TABLE_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redigera:.
        /// </summary>
        public static string TABLE_EDIT {
            get {
                return ResourceManager.GetString("TABLE_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel:.
        /// </summary>
        public static string TABLE_HEADING_TITLE {
            get {
                return ResourceManager.GetString("TABLE_HEADING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordning:.
        /// </summary>
        public static string TABLE_ORDER {
            get {
                return ResourceManager.GetString("TABLE_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position:.
        /// </summary>
        public static string TABLE_POSITION {
            get {
                return ResourceManager.GetString("TABLE_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vald:.
        /// </summary>
        public static string TABLE_SELECTED {
            get {
                return ResourceManager.GetString("TABLE_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editera Fråga!.
        /// </summary>
        public static string TEXT_ADMIN_QUESTION {
            get {
                return ResourceManager.GetString("TEXT_ADMIN_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nedan finns skapade frågor..
        /// </summary>
        public static string TEXT_HELP_1 {
            get {
                return ResourceManager.GetString("TEXT_HELP_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrera Fråga.
        /// </summary>
        public static string VIEW_BAG_TITLE {
            get {
                return ResourceManager.GetString("VIEW_BAG_TITLE", resourceCulture);
            }
        }
    }
}
