//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Condominium2000.Resources.Announcement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminAnnouncements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminAnnouncements() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    var temp = new global::System.Resources.ResourceManager("Condominium2000.Resources.Announcement.AdminAnnouncements", typeof(AdminAnnouncements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta Bort.
        /// </summary>
        public static string BUTTON_DELETE_ANNOUNCEMENT {
            get {
                return ResourceManager.GetString("BUTTON_DELETE_ANNOUNCEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editera.
        /// </summary>
        public static string BUTTON_EDIT_ANNOUNCEMENT {
            get {
                return ResourceManager.GetString("BUTTON_EDIT_ANNOUNCEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spara.
        /// </summary>
        public static string BUTTON_SAVE {
            get {
                return ResourceManager.GetString("BUTTON_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redigera utropet misslyckades. Var god rätta till felen och försök igen..
        /// </summary>
        public static string ERROR_EDIT_ANNOUNCEMENT {
            get {
                return ResourceManager.GetString("ERROR_EDIT_ANNOUNCEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fel uppstod, kunde inte hitta valt utrop!.
        /// </summary>
        public static string ERROR_INTERNAL_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_INTERNAL_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valt utrop har ändrats!.
        /// </summary>
        public static string SUCCESS_SELECTED_ANNOUNCEMENT_SAVED {
            get {
                return ResourceManager.GetString("SUCCESS_SELECTED_ANNOUNCEMENT_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum:.
        /// </summary>
        public static string TABLE_DATE_CREATED {
            get {
                return ResourceManager.GetString("TABLE_DATE_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort:.
        /// </summary>
        public static string TABLE_DELETE {
            get {
                return ResourceManager.GetString("TABLE_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redigera:.
        /// </summary>
        public static string TABLE_EDIT {
            get {
                return ResourceManager.GetString("TABLE_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel:.
        /// </summary>
        public static string TABLE_HEADING_TITLE {
            get {
                return ResourceManager.GetString("TABLE_HEADING_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vald:.
        /// </summary>
        public static string TABLE_SELECTED {
            get {
                return ResourceManager.GetString("TABLE_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editera Utrop.
        /// </summary>
        public static string TEXT_ADMIN_ANNOUNCEMENTS {
            get {
                return ResourceManager.GetString("TEXT_ADMIN_ANNOUNCEMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Välj vilket meddelande som ska visas på förstasidan. Observera att endast ett utrop kan vara valt!.
        /// </summary>
        public static string TEXT_HELP_1 {
            get {
                return ResourceManager.GetString("TEXT_HELP_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrera Utrop.
        /// </summary>
        public static string VIEW_BAG_TITLE {
            get {
                return ResourceManager.GetString("VIEW_BAG_TITLE", resourceCulture);
            }
        }
    }
}
