//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Condominium2000.Resources.Contact {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    var temp = new global::System.Resources.ResourceManager("Condominium2000.Resources.Contact.ErrorForm", typeof(ErrorForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cykelrum.
        /// </summary>
        public static string ENUM_VALUE_BICYCLE_ROOM {
            get {
                return ResourceManager.GetString("ENUM_VALUE_BICYCLE_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Källarförråd.
        /// </summary>
        public static string ENUM_VALUE_CELLAR {
            get {
                return ResourceManager.GetString("ENUM_VALUE_CELLAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innergården.
        /// </summary>
        public static string ENUM_VALUE_COURTYARD {
            get {
                return ResourceManager.GetString("ENUM_VALUE_COURTYARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiss/Trapphus.
        /// </summary>
        public static string ENUM_VALUE_ELEVATOR {
            get {
                return ResourceManager.GetString("ENUM_VALUE_ELEVATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garage.
        /// </summary>
        public static string ENUM_VALUE_GARAGE {
            get {
                return ResourceManager.GetString("ENUM_VALUE_GARAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sophantering.
        /// </summary>
        public static string ENUM_VALUE_GARBAGE_DISPOSAL {
            get {
                return ResourceManager.GetString("ENUM_VALUE_GARBAGE_DISPOSAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Övrigt.
        /// </summary>
        public static string ENUM_VALUE_GENERAL {
            get {
                return ResourceManager.GetString("ENUM_VALUE_GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gästrum.
        /// </summary>
        public static string ENUM_VALUE_GUEST_ROOM {
            get {
                return ResourceManager.GetString("ENUM_VALUE_GUEST_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Störningar.
        /// </summary>
        public static string ENUM_VALUE_NOISE {
            get {
                return ResourceManager.GetString("ENUM_VALUE_NOISE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relax.
        /// </summary>
        public static string ENUM_VALUE_RELAX {
            get {
                return ResourceManager.GetString("ENUM_VALUE_RELAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Värme/Vatten/Avlopp.
        /// </summary>
        public static string ENUM_VALUE_WATER {
            get {
                return ResourceManager.GetString("ENUM_VALUE_WATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hemsidan.
        /// </summary>
        public static string ENUM_VALUE_WEB_PAGE {
            get {
                return ResourceManager.GetString("ENUM_VALUE_WEB_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felformulär.
        /// </summary>
        public static string VIEW_BAG_TITLE {
            get {
                return ResourceManager.GetString("VIEW_BAG_TITLE", resourceCulture);
            }
        }
    }
}
